// Code generated by qtc from "model.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template/model.qtpl:1
package template

//line template/model.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template/model.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template/model.qtpl:1
func StreamModel(qw422016 *qt422016.Writer, name string) {
//line template/model.qtpl:1
	qw422016.N().S(`
type `)
//line template/model.qtpl:2
	qw422016.E().S(name)
//line template/model.qtpl:2
	qw422016.N().S(` struct{}
`)
//line template/model.qtpl:3
}

//line template/model.qtpl:3
func WriteModel(qq422016 qtio422016.Writer, name string) {
//line template/model.qtpl:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template/model.qtpl:3
	StreamModel(qw422016, name)
//line template/model.qtpl:3
	qt422016.ReleaseWriter(qw422016)
//line template/model.qtpl:3
}

//line template/model.qtpl:3
func Model(name string) string {
//line template/model.qtpl:3
	qb422016 := qt422016.AcquireByteBuffer()
//line template/model.qtpl:3
	WriteModel(qb422016, name)
//line template/model.qtpl:3
	qs422016 := string(qb422016.B)
//line template/model.qtpl:3
	qt422016.ReleaseByteBuffer(qb422016)
//line template/model.qtpl:3
	return qs422016
//line template/model.qtpl:3
}
