on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: go test --short ./...
